### PR TITLE
Try to improve ExplicitNonNullaryApply

### PR DESCRIPTION
**Pull request by dwijnand**
* use info.isJava again, as an initial, shallow, check
* move power.isJavaDefined as the last, most expensive, check
* shutdown and reset the compiler after two failures
* refactor methods & add some comments

Refs #47

### CODE REVIEW

**Comment by dwijnand** [comment]
cc @exoego do you think you could run this against your codebase to see how it fairs?

If it's easier, instead of having to checkout and publishLocal, I'm happy to merge it and you could try the -SNAPSHOT release that results from merging.

**Comment by exoego** [comment]
I will try within a few days.

**Comment by dwijnand** [comment]
It's released as `0.1.1+4-ec6df524-SNAPSHOT`:

* https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala-rewrites_2.13/0.1.1+4-ec6df524-SNAPSHOT/
* https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala-rewrites_2.12/0.1.1+4-ec6df524-SNAPSHOT/

**Comment by exoego** [comment]
@dwijnand 
I tried `0.1.1+4-ec6df524-SNAPSHOT` and it was much faster !

It completed in 64 seconds on small project, which took 300 seconds + with 0.1.1.
2nd run without no code change completed in 11 seconds.
It also completed in 154 seconds for medium-sized project (50K+ lines of Scala), where OOM had happened with 0.1.1.

**Comment by dwijnand** [comment]
That's great news!  I made another improvement in #49, which should publish soon: https://travis-ci.com/github/scala/scala-rewrites/jobs/357887909.  I'd be interested to know if and by how much that changes the times.

Thank you for that detail!

**Pull request merged**
